### ISSUE TITLE
Support the `banner` option

### ISSUE THREAD

**Issue by chalkygames123** [mahaker/esbuild-gas-plugin#12]
Hi, thank you for creating this plugin.

So I noticed that this plugin does not take esbuild's [`banner`](https://esbuild.github.io/api/#banner) option into account. Would you mind if I asked you to support it?

For example, a build with the following setup:

```javascript
// build.js
import * as esbuild from 'esbuild';
import {GasPlugin} from 'esbuild-gas-plugin';

await esbuild.build({
	entryPoints: ['src/main.js'],
	banner: {
		js: `/**
 * This is a banner.
 */
`,
	},
	outfile: 'dist/main.js',
	plugins: [GasPlugin],
});
```

```javascript
// src/main.js
global.foo = function () {};
```

will generates:

```javascript
var global = this;
/**
 * This is a banner.
 */
function foo() {
}
/**
 * This is a banner.
 */

global.foo = function() {
};
```

The banner is not at the top of the file and is duplicated.

**Comment by mahaker** [comment]
Thanks for the feedback!

It does indeed seem that the banner comment is not at the top of the code.
I will check it.

**Comment by mahaker** [comment]
New version v0.5.1 has been released.
https://github.com/mahaker/esbuild-gas-plugin/releases/tag/0.5.1

It includes support for the banner option for Node.js.
Support for Deno is in progress ⚒️ .
Please give it a try!

**Comment by chalkygames123** [comment]
Thank you, but I would like to add one more point: it looks to be missing one newline character at the end of the banner compared to the output without this plugin.

**Comment by mahaker** [comment]
Thank you for your comment.
I have released a version of the banner with a line break added at the end of the banner.
https://github.com/mahaker/esbuild-gas-plugin/releases/tag/0.5.2

Please give it a try!

**Comment by chalkygames123** [comment]
Great, now it works perfectly. Thank you!
